[package]
name = "rust_lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.1.5"
aws-sdk-s3 = "1.15.0"
aws-sdk-sts = "1.13.0"
